name: CI

on: [push]

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build
        run: |
          cmake -G "Visual Studio 15 2017" -A "$WINHOST" -S . -B "bin/windows-$WINHOST/$TARGET"
          cmake --build "bin/windows-$WINHOST/$TARGET"
        env:
          WINHOST: x64 
          TARGET: x86_64-linux-gnu
